# WEB-SV-2174
network:
  version: 2
  ethernets:
    ens3:
      dhcp4: false
      addresses:
        - 10.21.74.130/28
      routes:
        - to: default
          via: 10.21.74.129
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1
